# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

machine:
  enabled: true

jobs:
  checkout_code:
    working_directory: ~/circleci-stepwise
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/circleci-stepwise
  test:
    working_directory: ~/circleci-stepwise
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/circleci-stepwise
      - run: gradle test
  build:
    working_directory: ~/circleci-stepwise
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/circleci-stepwise
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/circleci-stepwise
      - run: gradle build


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build